// Generated by CoffeeScript 1.6.1
var exec, gitExec;

exec = require('child_process').exec;

gitExec = function(cmd, timeout, callback) {
  var git, result, timer;
  if (timeout == null) {
    timeout = 2000;
  }
  if (typeof timeout === 'function') {
    callback = timeout;
    timeout = 2000;
  }
  result = '';
  timer = setTimeout(function() {
    console.log('timeout call');
    if (!result) {
      return callback(null);
    }
  }, timeout);
  try {
    git = exec(cmd);
    git.stdout.on('data', function(data) {
      return result += data.trim();
    });
    return git.stdout.on('close', function() {
      clearTimeout(timer);
      return typeof callback === "function" ? callback(result) : void 0;
    });
  } catch (error) {
    console.log(error);
    clearTimeout(timer);
    return typeof callback === "function" ? callback(null) : void 0;
  }
};

module.exports = {
  getHash: function(fileName, callback) {
    return gitExec("git log -n 1 --pretty=\"%H\" -- " + fileName, callback);
  },
  diffMaster: function(fileName, timeout, callback) {
    return gitExec("git diff master -- " + fileName, timeout, callback);
  }
};
